### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by JinghuangLiu** [DamonMok/DMImagePickerTool#1]
当 初始化方法放在viewDidLoad方法下，设置不保存 记录上一次的选择 就失效了。

self.imagePickerVC = [[DMImagePickerController alloc] initWithMaxImagesCount:9];
self.imagePickerVC.maxImagesCount = 9;
self.imagePickerVC.allowRecordSelection = NO;
self.imagePickerVC.allowCrossSelect = NO;

**Comment by JinghuangLiu** [comment]
可以的话，尽快解决下。

**Comment by DamonMok** [comment]
已交流解决。
